version: '2'
services:
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser_pass
      MYSQL_ROOT_PASSWORD: root

  web:
    container_name: web
    command: bundle exec rdebug-ide --port 1234 --dispatcher-port 26162 --host 0.0.0.0 -- bin/rails s -b 0.0.0.0 -p 3000
    build: .
    ports:
      - "3000:3000"
      - "1234:1234"
      - "26162:26162"
    links:
      - db:db
    volumes:
      - .:/var/myapp
      - bundle:/mnt/bundle
volumes:
  bundle:
#    command: sh -c "bundle install --path=vendor/bundle && rm tmp/pids/server.pid; bin/rails s -b 0.0.0.0"
